-- Embed Insta schema

CREATE TABLE IF NOT EXISTS instagram_posts (
  id                   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  post_id              VARCHAR(64)   NOT NULL,
  shortcode            VARCHAR(64)   NULL,
  username             VARCHAR(128)  NULL,
  owner_full_name      VARCHAR(255)  NULL,
  owner_id             VARCHAR(64)   NULL,
  caption              TEXT          NULL,
  alt_text             TEXT          NULL,
  permalink            VARCHAR(512)  NULL,
  input_url            VARCHAR(512)  NULL,
  post_type            VARCHAR(32)   NULL,
  product_type         VARCHAR(32)   NULL,
  likes_count          INT UNSIGNED  NOT NULL DEFAULT 0,
  comments_count       INT UNSIGNED  NOT NULL DEFAULT 0,
  video_url            VARCHAR(2048) NULL,
  video_view_count     INT UNSIGNED  NULL,
  video_play_count     INT UNSIGNED  NULL,
  video_duration       DECIMAL(10,3) NULL,
  dimensions_width     INT UNSIGNED  NULL,
  dimensions_height    INT UNSIGNED  NULL,
  location_name        VARCHAR(255)  NULL,
  location_id          VARCHAR(64)   NULL,
  music_song           VARCHAR(255)  NULL,
  music_artist         VARCHAR(255)  NULL,
  music_audio_id       VARCHAR(64)   NULL,
  hashtags             TEXT          NULL,
  mentions             TEXT          NULL,
  tagged_users_json    LONGTEXT      NULL,
  coauthors_json       LONGTEXT      NULL,
  first_comment        TEXT          NULL,
  is_pinned            TINYINT(1)    NOT NULL DEFAULT 0,
  is_comments_disabled TINYINT(1)    NOT NULL DEFAULT 0,
  posted_at            DATETIME      NULL,
  raw_json             LONGTEXT      NULL,
  created_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_post_id (post_id),
  KEY idx_username_posted_at (username, posted_at),
  KEY idx_posted_at (posted_at),
  KEY idx_shortcode (shortcode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS instagram_media (
  id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  post_id        VARCHAR(64)   NOT NULL,
  position       INT UNSIGNED  NOT NULL DEFAULT 0,
  child_post_id  VARCHAR(64)   NULL,
  child_shortcode VARCHAR(64)  NULL,
  media_type     VARCHAR(16)   NOT NULL,
  media_url      VARCHAR(2048) NOT NULL,
  local_path     VARCHAR(1024) NULL,
  thumbnail_url  VARCHAR(2048) NULL,
  alt_text       TEXT          NULL,
  width          INT UNSIGNED  NULL,
  height         INT UNSIGNED  NULL,
  created_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_post_id (post_id),
  CONSTRAINT fk_media_post FOREIGN KEY (post_id) REFERENCES instagram_posts (post_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS embed_users (
  id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  username      VARCHAR(64)   NOT NULL,
  email         VARCHAR(191)  NULL,
  password_hash VARCHAR(255)  NOT NULL,
  display_name  VARCHAR(128)  NULL,
  is_active     TINYINT(1)    NOT NULL DEFAULT 1,
  last_login_at DATETIME      NULL,
  created_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_embed_user_username (username),
  UNIQUE KEY uq_embed_user_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS widget_settings (
  id              INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name            VARCHAR(64)   NOT NULL DEFAULT 'default',
  title           VARCHAR(128)  NULL,
  targets_json    TEXT          NULL,
  layout          VARCHAR(16)   NOT NULL DEFAULT 'grid',
  columns         TINYINT UNSIGNED NOT NULL DEFAULT 3,
  card_radius     TINYINT UNSIGNED NOT NULL DEFAULT 8,
  gap             TINYINT UNSIGNED NOT NULL DEFAULT 12,
  show_caption    TINYINT(1)    NOT NULL DEFAULT 1,
  show_stats      TINYINT(1)    NOT NULL DEFAULT 1,
  show_username   TINYINT(1)    NOT NULL DEFAULT 1,
  accent_color    VARCHAR(16)   NOT NULL DEFAULT '#0095f6',
  background      VARCHAR(16)   NOT NULL DEFAULT '#ffffff',
  text_color      VARCHAR(16)   NOT NULL DEFAULT '#262626',
  border_color    VARCHAR(16)   NOT NULL DEFAULT '#dbdbdb',
  font_family     VARCHAR(128)  NOT NULL DEFAULT 'system-ui',
  max_items       SMALLINT UNSIGNED NOT NULL DEFAULT 9,
  updated_by      BIGINT UNSIGNED NULL,
  created_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_widget_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO widget_settings (name, title) VALUES ('default', 'Default widget');

CREATE TABLE IF NOT EXISTS instagram_comments (
  id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  post_id         VARCHAR(64)   NOT NULL,
  comment_id      VARCHAR(64)   NOT NULL,
  owner_username  VARCHAR(128)  NULL,
  owner_id        VARCHAR(64)   NULL,
  text            TEXT          NULL,
  likes_count     INT UNSIGNED  NOT NULL DEFAULT 0,
  replies_count   INT UNSIGNED  NOT NULL DEFAULT 0,
  parent_comment_id VARCHAR(64) NULL,
  posted_at       DATETIME      NULL,
  created_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_comment (post_id, comment_id),
  KEY idx_post_id (post_id),
  CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES instagram_posts (post_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
